version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_NAME=auth_db
      - DATABASE_PASSWORD=postgres
      - DATABASE_SSLMODE=disable
    ports:
      - "5432:5432"